version: '3'

services:

  app:
    build:
      context: ./
    container_name: app
    restart: always
    tty: true
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db
    networks:
      - nodenet

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nodenet

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80" 
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge